/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 5.7 */
/* Wed Jul  1 22:06:14 2015 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .CLKOS3( ));
